source("Classes/16s18sits_module.R")

getpipeline<-function(){
  new("pipeline",
      id = "16s18sits",
      name = "16S-18S/ITS",
      version = 1.0,
      image = "images/16srrna.png",
      steps = list(
        statusb = list(folder="0-raw",
                       software="MultiQC",
                       version="1.7",#system("multiqc --version |tail -n1 | awk '{print $NF}'",intern = T),
                       spath=system("which multiqc",intern = T),
                       stepName="Reads before QC",
                       stepID="rbqc",
                       icon = icon("stream"),
                       iconHTML='fa fa-stream',
                       tabcontentUI=list(ui=statusbUIm, 
                                         id="statusbmodule"),
                       tabcontentSrv=list(server=statusbTabModule,
                                          id="statusbmodule")),
        qc = list(folder="1-qc",
                  software="DADA2",
                  version=packageVersion("dada2"),
                  spath=system("which multiqc",intern = T),
                  stepName="QC status",
                  stepID="qc",
                  icon = icon("filter"),
                  iconHTML='fa fa-filter',
                  tabcontentUI=list(ui=qcUIm, 
                                    id="statusbmodule"),
                  tabcontentSrv=list(server=qcModule,
                                     id="statusbmodule")),
        statusa = list(folder="1-qc",
                       software="MultiQC",
                       version="1.7",#system("multiqc --version |tail -n1 | awk '{print $NF}'",intern = T),
                       spath=system("which multiqc",intern = T),
                       stepName="Reads after QC",
                       stepID="raqc",
                       icon = icon("stream"),
                       iconHTML='fa fa-stream',
                       tabcontentUI=list(ui=statusbUIm, 
                                         id="statusbmodule"),
                       tabcontentSrv=list(server=statusbTabModule,
                                          id="statusbmodule")),
        taxInsight = list(folder="2-taxInsight",
                          software="dada2",
                          version="0.0.0",
                          stepName="Taxonomic counts",
                          stepID="tc",
                          icon = icon("microscope"),
                          iconHTML='fa fa-microscope',
                          tabcontentUI=list(ui=statusbUIm, 
                                            id="statusbmodule"),
                          tabcontentSrv=list(server=statusbTabModule,
                                             id="statusbmodule"))
      ),
      stepsOptions = list(
        color = "danger",
        collapsed = T
      )
  )
}